#!/bin/sh

# extra options remove the possibility to try to power-off mounted partitions 
# and the primary drive (root directory, home directory and the EFI partition)
udisksctl power-off -b $(lsblk -lp | awk '/part/ && !/sda/ && $7=="" {print $1, "(" $4 ")"}' | dmenu -p poweroff)
